-- MySQL Script generated by MySQL Workbench
-- mer. 27 juin 2018 14:01:55 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NULL,
  `password` VARCHAR(128) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB
COMMENT = '1. Maquetter une application\n\n2. Réaliser une interface utilisateur web statique et adaptable\n\n3. Développer une interface utilisateur web dynamique\n\n4. Réaliser une interface utilisateur avec une solution de\ngestion de contenu ou e-commerce\n\n5. Créer une base de données\n\n6. Développer les composants d’accès aux données\n\n7. Développer la partie back-end d’une application web ou\nweb mobile\n\n8. Elaborer et mettre en œuvre des composants dans une\napplication de gestion de contenu ou e-commerce\n\n9. Utiliser l’anglais dans son activité professionnelle en développement web et web mobile\n\n10. Actualiser et partager ses compétences en développement web et web mobile\n\n';


-- -----------------------------------------------------
-- Table `mydb`.`Competences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competences` (
  `idCompétences` INT NOT NULL AUTO_INCREMENT,
  `competence1` INT NULL,
  `competence2` INT NULL,
  `competence3` INT NULL,
  `competence4` INT NULL,
  `competence6` INT NULL,
  `competence7` INT NULL,
  `competence8` INT NULL,
  `competence9` INT NULL,
  `competence10` INT NULL,
  PRIMARY KEY (`idCompétences`))
ENGINE = MEMORY
COMMENT = '1. Maquetter une application\n\n2. Réaliser une interface utilisateur web statique et\nadaptable\n\n3. Développer une interface utilisateur web dynamique\n\n4. Réaliser une interface utilisateur avec une solution de\ngestion de contenu ou e-commerce\n\n5. Créer une base de données\n\n6. Développer les composants d’accès aux données\n\n7. Développer la partie back-end d’une application web ou\nweb mobile\n\n8. Elaborer et mettre en œuvre des composants dans une\napplication de gestion de contenu ou e-commerce\n\n9. Utiliser l’anglais dans son activité professionnelle en développement web et web mobile\n\n10. Actualiser et partager ses compétences en développement web et web mobile';


-- -----------------------------------------------------
-- Table `mydb`.`Competences_vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competences_vote` (
  `idCompétences` INT NOT NULL AUTO_INCREMENT,
  `competence1` INT NULL,
  `competence2` INT NULL,
  `competence3` INT NULL,
  `competence4` INT NULL,
  `competence6` INT NULL,
  `competence7` INT NULL,
  `competence8` INT NULL,
  `competence9` INT NULL,
  `competence10` INT NULL,
  PRIMARY KEY (`idCompétences`))
ENGINE = MEMORY
COMMENT = '1. Maquetter une application\n\n2. Réaliser une interface utilisateur web statique et\nadaptable\n\n3. Développer une interface utilisateur web dynamique\n\n4. Réaliser une interface utilisateur avec une solution de\ngestion de contenu ou e-commerce\n\n5. Créer une base de données\n\n6. Développer les composants d’accès aux données\n\n7. Développer la partie back-end d’une application web ou\nweb mobile\n\n8. Elaborer et mettre en œuvre des composants dans une\napplication de gestion de contenu ou e-commerce\n\n9. Utiliser l’anglais dans son activité professionnelle en développement web et web mobile\n\n10. Actualiser et partager ses compétences en développement web et web mobile';


-- -----------------------------------------------------
-- Table `mydb`.`Voteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voteur` (
  `idVoteur` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idVoteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Note` (
  `Date` VARCHAR(45) NULL,
  `idClient` VARCHAR(45) NULL,
  `idCompétences` VARCHAR(45) NULL,
  `Client_idClient` INT NOT NULL,
  `Competences_idCompétences` INT NOT NULL,
  `Competences_vote_idCompétences` INT NOT NULL,
  `Voteur_idVoteur` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Competences_idCompétences`, `Competences_vote_idCompétences`),
  INDEX `fk_Data_Competences1_idx` (`Competences_idCompétences` ASC),
  INDEX `fk_Data_Competences_vote1_idx` (`Competences_vote_idCompétences` ASC),
  INDEX `fk_Note_Voteur1_idx` (`Voteur_idVoteur` ASC),
  CONSTRAINT `fk_Data_Client`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Data_Competences1`
    FOREIGN KEY (`Competences_idCompétences`)
    REFERENCES `mydb`.`Competences` (`idCompétences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Data_Competences_vote1`
    FOREIGN KEY (`Competences_vote_idCompétences`)
    REFERENCES `mydb`.`Competences_vote` (`idCompétences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Voteur1`
    FOREIGN KEY (`Voteur_idVoteur`)
    REFERENCES `mydb`.`Voteur` (`idVoteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
